In [110]:
#pdb 딕셔너리
import numpy as np
def parsing_pdb(pdb_file):
    with open(pdb_file, 'r') as file:
        xyz={}
        for line in file:
            if line.startswith("ATOM"):
                atom_name=line[12:16].strip()
                if atom_name not in xyz:
                    
                    xyz[atom_name]={}
                        
                residue_num=int(line[22:26].strip())
                        
                if residue_num not in xyz[atom_name]:
                    xyz[atom_name][residue_num]={}
                
                xyz[atom_name][residue_num]=[float(line[30:38].strip()),float(line[38:46].strip()),float(line[46:54].strip())]
                
    return xyz

pdb_file='/Users/kistintern6/ProteinAnalysis/Day1/PDBex.pdb'

#print(parsing_pdb(pdb_file))
parsing_dict=parsing_pdb(pdb_file)
print(parsing_dict)


{'N': {1: [27.34, 24.43, 2.614], 2: [26.335, 27.77, 3.258], 3: [26.849, 29.656, 6.217], 4: [26.214, 32.097, 8.771], 5: [28.26, 33.943, 11.096], 6: [27.751, 35.867, 13.74], 7: [29.426, 38.43, 15.446], 8: [30.132, 40.069, 18.642], 9: [30.991, 42.571, 17.998], 10: [29.721, 43.673, 15.885], 11: [30.563, 42.623, 13.495], 12: [30.163, 40.338, 10.886], 13: [30.795, 37.015, 10.095], 14: [31.244, 34.986, 7.197], 15: [30.884, 31.485, 6.666], 16: [31.834, 28.412, 5.125], 17: [30.31, 25.458, 5.384], 18: [29.38, 22.057, 6.232], 19: [26.559, 20.22, 7.288], 20: [27.361, 17.959, 8.559], 21: [29.599, 18.599, 9.828], 22: [31.51, 18.936, 12.852], 23: [31.113, 20.863, 15.86], 24: [33.548, 21.526, 16.95], 25: [35.139, 21.624, 14.662], 26: [34.007, 23.745, 13.25], 27: [34.734, 25.822, 14.949], 28: [37.499, 25.743, 14.571], 29: [37.633, 26.543, 11.867], 30: [36.811, 29.17, 12.192], 31: [38.883, 30.11, 13.713], 32: [41.001, 29.878, 11.931], 33: [40.117, 31.75, 9.988], 34: [39.655, 34.335, 11.285], 35: [41.317

In [111]:
#'N'dict
Ndict={}

Ndict['N']=parsing_dict.get('N')
print(Ndict)
print("")

#'O'dict
Odict={}

Odict['O']=parsing_dict.get('O')
print(Odict)




{'N': {1: [27.34, 24.43, 2.614], 2: [26.335, 27.77, 3.258], 3: [26.849, 29.656, 6.217], 4: [26.214, 32.097, 8.771], 5: [28.26, 33.943, 11.096], 6: [27.751, 35.867, 13.74], 7: [29.426, 38.43, 15.446], 8: [30.132, 40.069, 18.642], 9: [30.991, 42.571, 17.998], 10: [29.721, 43.673, 15.885], 11: [30.563, 42.623, 13.495], 12: [30.163, 40.338, 10.886], 13: [30.795, 37.015, 10.095], 14: [31.244, 34.986, 7.197], 15: [30.884, 31.485, 6.666], 16: [31.834, 28.412, 5.125], 17: [30.31, 25.458, 5.384], 18: [29.38, 22.057, 6.232], 19: [26.559, 20.22, 7.288], 20: [27.361, 17.959, 8.559], 21: [29.599, 18.599, 9.828], 22: [31.51, 18.936, 12.852], 23: [31.113, 20.863, 15.86], 24: [33.548, 21.526, 16.95], 25: [35.139, 21.624, 14.662], 26: [34.007, 23.745, 13.25], 27: [34.734, 25.822, 14.949], 28: [37.499, 25.743, 14.571], 29: [37.633, 26.543, 11.867], 30: [36.811, 29.17, 12.192], 31: [38.883, 30.11, 13.713], 32: [41.001, 29.878, 11.931], 33: [40.117, 31.75, 9.988], 34: [39.655, 34.335, 11.285], 35: [41.317

In [112]:
print(len(Ndict['N']))
print(len(Odict['O']))

76
76


In [113]:
print(Odict['O'][1])

[27.886, 26.463, 4.263]


In [130]:
#Odict
OList=[]
for i in range(len(Odict['O'])):
    k=Odict['O'][i+1]
    OList.append(k)
matrixO=np.array(OList)
print(matrixO[0])
print(matrixO[75])
print("")
print(len(matrixO))

#NList
NList=[]
for j in range(len(Ndict['N'])):
    k=Ndict['N'][j+1]
    NList.append(k)
matrixN=np.array(NList)

'''
print(matrixN[0])
print(matrixN[75])
print("")
print(matrixO[0]-matrixN[0])
print(matrixO[0]-matrixN[75])

print("")
print(np.linalg.norm(matrixO[0]-matrixN[0]))
print(np.linalg.norm(matrixO[0]-matrixN[1]))
'''

[27.886 26.463  4.263]
[38.933 40.525 35.687]

76
[27.34  24.43   2.614]
[40.946 38.472 33.757]

[0.546 2.033 1.649]
[-13.06  -12.009 -29.494]

2.674024308042095
2.263597799963587


In [164]:
ONList=np.zeros((76,76))
ONList

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [174]:
#O-N adjacent matrix
cols=len(NList)
rows=len(OList)

ONList=np.zeros((76,76))
# ONList=[[0]*cols]*rows=> numpy를 이용하여 배열 선언해줘야함. 안그러면 오류남.

for i in range(len(OList)):
    
    for j in range(len(NList)):
        difference=matrixO[i]-matrixN[j]
        l2norm=np.linalg.norm(difference)
        ONList[i][j]=l2norm

print(ONList)

[[ 2.67402431  2.2635978   3.88442196 ... 28.83214506 31.97270226
  34.41911848]
 [ 5.8827814   2.83312548  2.26328279 ... 28.8007953  31.84163427
  33.99937638]
 [ 8.65770276  5.83502853  2.53702247 ... 25.20257737 28.23521626
  30.29243751]
 ...
 [33.72505125 32.7831344  29.68631698 ...  3.11961039  2.27727776
   5.11534564]
 [34.96292735 33.63483108 30.34801125 ...  4.85594584  3.01901259
   2.26295957]
 [38.56513974 37.05454992 33.65470423 ...  9.12892403  6.65420025
   3.46292911]]


In [175]:
#N-O adjacent matrix
cols=len(OList)
rows=len(NList)

NOList=np.zeros((76,76))
# ONList=[[0]*cols]*rows=> numpy를 이용하여 배열 선언해줘야함. 안그러면 오류남.

for i in range(len(NList)):
    
    for j in range(len(OList)):
        difference=matrixN[i]-matrixO[j]
        l2norm=np.linalg.norm(difference)
        NOList[i][j]=l2norm

print(NOList)

[[ 2.67402431  5.8827814   8.65770276 ... 33.72505125 34.96292735
  38.56513974]
 [ 2.2635978   2.83312548  5.83502853 ... 32.7831344  33.63483108
  37.05454992]
 [ 3.88442196  2.26328279  2.53702247 ... 29.68631698 30.34801125
  33.65470423]
 ...
 [28.83214506 28.8007953  25.20257737 ...  3.11961039  4.85594584
   9.12892403]
 [31.97270226 31.84163427 28.23521626 ...  2.27727776  3.01901259
   6.65420025]
 [34.41911848 33.99937638 30.29243751 ...  5.11534564  2.26295957
   3.46292911]]


In [183]:
#O-N min value
min_value=ONList.min()
print(min_value)
min_index=ONList.argmin()
print(min_index)
print(ONList[8][9])
min_index_2d = np.unravel_index(min_index, ONList.shape)
min_index_2d_plus=tuple(i+1 for i in min_index_2d)
print(min_index_2d_plus)

2.2031754355929074
617
2.2031754355929074
(9, 10)


In [200]:
#Impossible Bonding
#ONList
import pandas as pd
ONimbonding=[]
for i in range(len(OList)):
    for j in range(len(NList)):
        if ONList[i][j] < 3.5:
            ONimbonding.append((("Residue "+str(i+1)+".O"),("Residue "+str(j+1)+".N")))

ONarray=np.array(ONimbonding)

df = pd.DataFrame(ONarray, columns=["O", "N"])
grouped=df.groupby("O")
print(grouped)

for name, group in grouped:
    print("Group", name)
    print(group)
    print()

Group Residue 1.O
             O             N
0  Residue 1.O   Residue 1.N
1  Residue 1.O   Residue 2.N
2  Residue 1.O  Residue 17.N

Group Residue 10.O
               O             N
25  Residue 10.O  Residue 11.N

Group Residue 11.O
               O             N
26  Residue 11.O   Residue 7.N
27  Residue 11.O  Residue 11.N
28  Residue 11.O  Residue 12.N

Group Residue 12.O
               O             N
29  Residue 12.O  Residue 12.N
30  Residue 12.O  Residue 13.N

Group Residue 13.O
               O             N
31  Residue 13.O   Residue 5.N
32  Residue 13.O  Residue 13.N
33  Residue 13.O  Residue 14.N

Group Residue 14.O
               O             N
34  Residue 14.O  Residue 14.N
35  Residue 14.O  Residue 15.N

Group Residue 15.O
               O             N
36  Residue 15.O   Residue 3.N
37  Residue 15.O  Residue 15.N
38  Residue 15.O  Residue 16.N

Group Residue 16.O
               O             N
39  Residue 16.O  Residue 16.N
40  Residue 16.O  Residue 17.N

Group Residu

In [188]:
#Impossible Bonding
#NOList
NOimbonding=[]
for i in range(len(NList)):
    for j in range(len(OList)):
        if NOList[i][j] < 3.5:
            
            NOimbonding.append((i+1,j+1))

print(NOimbonding)

[(1, 1), (1, 17), (2, 1), (2, 2), (3, 2), (3, 3), (3, 15), (4, 3), (4, 4), (4, 65), (5, 4), (5, 5), (5, 13), (6, 5), (6, 6), (6, 67), (7, 6), (7, 7), (7, 11), (8, 7), (9, 7), (9, 8), (10, 7), (10, 9), (11, 9), (11, 10), (11, 11), (12, 11), (12, 12), (13, 5), (13, 12), (13, 13), (14, 13), (14, 14), (15, 3), (15, 14), (15, 15), (16, 15), (16, 16), (17, 1), (17, 16), (17, 17), (18, 17), (18, 18), (19, 18), (20, 18), (20, 19), (21, 18), (21, 19), (21, 20), (21, 21), (22, 21), (22, 22), (23, 22), (23, 52), (23, 54), (24, 22), (24, 23), (24, 52), (25, 22), (25, 23), (25, 24), (26, 22), (26, 23), (26, 25), (26, 26), (27, 23), (27, 24), (27, 25), (27, 26), (28, 24), (28, 25), (28, 26), (28, 27), (29, 25), (29, 26), (29, 28), (30, 26), (30, 27), (30, 28), (30, 29), (31, 27), (31, 28), (31, 29), (31, 30), (32, 28), (32, 29), (32, 30), (32, 31), (33, 29), (33, 30), (33, 31), (33, 32), (34, 30), (34, 33), (35, 31), (35, 34), (36, 34), (36, 35), (36, 36), (37, 35), (37, 36), (37, 37), (38, 36), (38

In [232]:
#Impossible HBond in O-N
ONimbonding = []
for i in range(len(OList)):
    for j in range(len(NList)):
        if ONList[i][j] < 3.5:
            ONimbonding.append((("Residue "+str(i+1)+".O"),("Residue "+str(j+1)+".N")))

#print(ONimbonding)
# Convert the list to dictionary
ON_dict = {}
nlist=[]
for item in ONimbonding:
    
    residue_o, residue_n = item
    #GPT reference
    #if residue_o not in ON_dict:
        #ON_dict[residue_o]=[]
    #ON_dict[residue_o].append(residue_n)
    
    #MyOwn
    nlist.append(residue_n)
    if residue_o not in ON_dict:
        ON_dict[residue_o]={}
    ON_dict[residue_o]=np.array(nlist)
    
#print(ON_dict)
print()
print(ON_dict['Residue 1.O'])


['Residue 1.N' 'Residue 2.N' 'Residue 17.N']


In [234]:
#Impossible HBond in N-O
NOimbonding = []
for i in range(len(NList)):
    for j in range(len(OList)):
        if NOList[i][j] < 3.5:
            NOimbonding.append((("Residue "+str(i+1)+".N"),("Residue "+str(j+1)+".O")))

#print(NOimbonding)
# Convert the list to dictionary
NO_dict = {}
olist=[]
for item in NOimbonding:
    
    residue_n, residue_o = item
    #GPT reference
    #if residue_n not in NO_dict:
        #NO_dict[residue_n]=[]
    #NO_dict[residue_n].append(residue_o)
    
    #MyOwn
    olist.append(residue_o)
    if residue_n not in NO_dict:
        NO_dict[residue_n]={}
    NO_dict[residue_n]=np.array(olist)
    
print(NO_dict)
print()
print(NO_dict['Residue 1.N'])

{'Residue 1.N': array(['Residue 1.O', 'Residue 17.O'], dtype='<U12'), 'Residue 2.N': array(['Residue 1.O', 'Residue 17.O', 'Residue 1.O', 'Residue 2.O'],
      dtype='<U12'), 'Residue 3.N': array(['Residue 1.O', 'Residue 17.O', 'Residue 1.O', 'Residue 2.O',
       'Residue 2.O', 'Residue 3.O', 'Residue 15.O'], dtype='<U12'), 'Residue 4.N': array(['Residue 1.O', 'Residue 17.O', 'Residue 1.O', 'Residue 2.O',
       'Residue 2.O', 'Residue 3.O', 'Residue 15.O', 'Residue 3.O',
       'Residue 4.O', 'Residue 65.O'], dtype='<U12'), 'Residue 5.N': array(['Residue 1.O', 'Residue 17.O', 'Residue 1.O', 'Residue 2.O',
       'Residue 2.O', 'Residue 3.O', 'Residue 15.O', 'Residue 3.O',
       'Residue 4.O', 'Residue 65.O', 'Residue 4.O', 'Residue 5.O',
       'Residue 13.O'], dtype='<U12'), 'Residue 6.N': array(['Residue 1.O', 'Residue 17.O', 'Residue 1.O', 'Residue 2.O',
       'Residue 2.O', 'Residue 3.O', 'Residue 15.O', 'Residue 3.O',
       'Residue 4.O', 'Residue 65.O', 'Residue 4.O', 'Resid